/*
 * docs.mjs — the glossary, written out where people read it. Node only.
 *
 * The Info pages on the Move take their definitions from TERMS in info.mjs.
 * The same definitions go into two more places — the Terms page of help.json,
 * which Schwung's Help viewer shows, and the glossary table in the README — so
 * they are generated here from that one source rather than kept by hand in
 * three. `npm run docs` writes them; tests/docs.test.mjs fails if either is
 * out of date.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { TERMS, wrapLines } from '../src/info.mjs';

const HELP_WIDTH = 25;   /* the widest line the hand-written help pages use */
export const README_START = '<!-- glossary:start (generated by npm run docs) -->';
export const README_END = '<!-- glossary:end -->';

export function termsPage() {
  const lines = [];
  for (const key of Object.keys(TERMS)) {
    const [name, text] = TERMS[key];
    if (lines.length) lines.push('');
    lines.push(name);
    const body = wrapLines([{ text, head: false }], HELP_WIDTH - 2, (s) => s.length);
    for (const l of body) lines.push('  ' + l.text);
  }
  return { title: 'Terms', lines };
}

/* help.json with its Terms page replaced, or added at the end. */
export function helpWithTerms(help) {
  const page = termsPage();
  const children = help.children.filter((c) => c.title !== 'Terms').concat([page]);
  return { ...help, children };
}

export function glossaryTable() {
  const rows = Object.keys(TERMS).map((k) => '| **' + TERMS[k][0] + '** | ' + TERMS[k][1] + ' |');
  return ['| Term | Meaning |', '| --- | --- |'].concat(rows).join('\n');
}

export function readmeWithGlossary(readme) {
  const a = readme.indexOf(README_START);
  const b = readme.indexOf(README_END);
  if (a < 0 || b < a) throw new Error('README has no glossary markers');
  return readme.slice(0, a + README_START.length) + '\n' + glossaryTable() + '\n' + readme.slice(b);
}

const HELP = new URL('../src/help.json', import.meta.url);
const README = new URL('../README.md', import.meta.url);

export function expected() {
  const help = JSON.stringify(helpWithTerms(JSON.parse(readFileSync(HELP, 'utf8'))), null, 2) + '\n';
  const readme = readmeWithGlossary(readFileSync(README, 'utf8'));
  return { help, readme };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { help, readme } = expected();
  writeFileSync(HELP, help);
  writeFileSync(README, readme);
  console.log('help.json Terms page and README glossary written.');
}
